In [1]:
!pip install pymongo pandas certifi

Requirement already satisfied: pymongo in /opt/anaconda3/envs/MLOps1/lib/python3.12/site-packages (4.16.0)
Requirement already satisfied: pandas in /opt/anaconda3/envs/MLOps1/lib/python3.12/site-packages (3.0.0)
Requirement already satisfied: certifi in /opt/anaconda3/envs/MLOps1/lib/python3.12/site-packages (2026.1.4)
Requirement already satisfied: dnspython<3.0.0,>=2.6.1 in /opt/anaconda3/envs/MLOps1/lib/python3.12/site-packages (from pymongo) (2.8.0)
Requirement already satisfied: numpy>=1.26.0 in /opt/anaconda3/envs/MLOps1/lib/python3.12/site-packages (from pandas) (2.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/envs/MLOps1/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/envs/MLOps1/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd
import pymongo
import certifi

In [3]:
df = pd.read_csv("Crop_recommendation.csv")

print(df.shape)
df.head()

(2200, 8)

    N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

In [4]:
data = df.to_dict(orient="records")

print(f"Total records: {len(data)}")

Total records: 2200

In [6]:
DB_NAME = "Krishisevak1"

COLLECTION_NAME = "crop_recommendation_data"

CONNECTION_URL = "mongodb+srv://dhruvkul2004_db_user:y5y2bpicKSzgISeQ@cluster0.jmkhkmt.mongodb.net/?appName=Cluster0"

In [7]:
client = pymongo.MongoClient(
    CONNECTION_URL,
    tlsCAFile=certifi.where()
)

db = client[DB_NAME]

collection = db[COLLECTION_NAME]

print("Connected Successfully")

Connected Successfully

In [8]:
result = collection.insert_many(data)

print("Inserted Records:", len(result.inserted_ids))

Inserted Records: 2200

In [9]:
uploaded_df = pd.DataFrame(
    list(collection.find())
)

uploaded_df.head()

,_id,N,P,K,temperature,humidity,ph,rainfall,label
0,6a3b48e191589d5298c5a247,90,42,43,20.879744,82.002744,6.502985,202.935536,rice
1,6a3b48e191589d5298c5a248,85,58,41,21.770462,80.319644,7.038096,226.655537,rice
2,6a3b48e191589d5298c5a249,60,55,44,23.004459,82.320763,7.840207,263.964248,rice
3,6a3b48e191589d5298c5a24a,74,35,40,26.491096,80.158363,6.980401,242.864034,rice
4,6a3b48e191589d5298c5a24b,78,42,42,20.130175,81.604873,7.628473,262.717340,rice

In [10]:
collection.count_documents({})

2200